
name: Test Code FreeBSD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: no
          release: "14.1"
          prepare: |
            pkg install -y curl git go

          run: |
            set -x
            go build -o netbird client/main.go
            whoami
            go test -timeout 5m ./...
