
name: Test Code FreeBSD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          envs: 'MYTOKEN MYTOKEN2'
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y git

          run: |
            set -x
            curl -o go.tar.gz https://go.dev/dl/go1.21.7.freebsd-amd64.tar.gz -L
            tar zxf go.tar.gz
            mv go /usr/local/go
            ln -s /usr/local/go/bin/go /usr/local/bin/go
            git clone https://github.com/netbirdio/netbird.git
            cd netbird
            go mod tidy
            go test -v ./client/...



