on:
  push:
name: Test Code Windows
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: cd client && bash -x wireguard_nt.sh
#        working-directory: client
      - run: ls -l client/*syso
      - uses: actions/upload-artifact@v2
        with:
          name: syso
          path: client/*.syso
          retention-days: 1

  test:
    needs: pre
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/download-artifact@v2
        with:
          name: syso
      - run: ls client/

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test  -tags load_wgnt_from_rsrc -p 1 ./...