
name: Test Code FreeBSD

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          release: "14.1"
          prepare: |
            pkg install -y go

          # -x - to print all executed commands
          # -e - to faile on first error
          run: |
            set -e -x
            go build -o netbird client/main.go
            # check all component except management, since we do not support management server on freebsd
            go test -timeout 5m -failfast ./base62/...
            go test -timeout 5m -failfast ./client/...
            go test -timeout 5m -failfast ./dns/...
            go test -timeout 5m -failfast ./encryption/...
            go test -timeout 5m -failfast ./formatter/...
            go test -timeout 5m -failfast ./iface/...
            go test -timeout 5m -failfast ./route/...
            go test -timeout 5m -failfast ./sharedsock/...
            go test -timeout 5m -failfast ./signal/...
            go test -timeout 5m -failfast ./util/...
            go test -timeout 5m -failfast ./version/...
