on:
  push:
name: Test Code Windows
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: bash -x wireguard_nt.sh
        working-directory: client
      - run: ls -l client/*syso
      - uses: actions/upload-artifact@v2
        with:
          name: syso
          path: client/*.syso
          retention-days: 1

  test:
    needs: pre
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: syso
          path: client\
      - run: ls client\
      - name: Test
        run: go test  -tags=load_wgnt_from_rsrc -p 1 ./wiretrustee/iface
      - name: Cache Go modules
        if: always()
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-