on:
  push:
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: GOBIN=$(which go) && sudo --preserve-env=GOROOT $GOBIN test -p 1 ./...

  test_build:
    strategy:
      matrix:
        os: [ windows, linux, darwin ]
        go-version: [1.17.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install modules
        run: go mod tidy

      - name: output limits curr user
        run: ulimit -a
      - name: output limits root user
        run: sudo bash -c 'ulimit -a' || true
      - name: cat limits.conf
        run: cat /etc/security/limits.conf
      - name: update limits.d
        run: |
          cat <<'EOF' | sudo tee -a /etc/security/limits.d/wt.conf
          root soft     nproc          65535
          root hard     nproc          65535
          root soft     nofile         65535
          root hard     nofile         65535
          $(whoami) soft     nproc          65535
          $(whoami) hard     nproc          65535
          $(whoami) soft     nofile         65535
          $(whoami) hard     nofile         65535
          EOF
      - name: output limits curr user after
        run: ulimit -a
      - name: output limits root user after
        run: sudo bash -c 'ulimit -a' || true

      - name: run build client
        run: GOOS=${{ matrix.os }} go build .
        working-directory: client

      - name: run build management
        run: GOOS=${{ matrix.os }} go build .
        working-directory: management

      - name: run build signal
        run: GOOS=${{ matrix.os }} go build .
        working-directory: signal