on:
  push:
name: Test Code Windows
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: bash -x wireguard_nt.sh
        working-directory: client
      - run: ls -l client/*syso
      - uses: actions/upload-artifact@v2
        with:
          name: syso
          path: |
            client/*.syso
            client/.deps/wireguard-nt/bin/amd64/wireguard.dll
          retention-days: 1

  test:
    needs: pre
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v2
        if: always()
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: syso
#          path: client\
      - run: ls
      - run: cp  .deps\wireguard-nt\bin\amd64\wireguard.dll wireguard.dll
      - run: cp  wireguard.dll client\wireguard.dll

      - name: Test
        run: go test -p 1 ./iface


