name: Test Code Darwin
on: [push,pull_request]

jobs:
  test-on-push:
    if: github.event_name != 'pull_request'
    uses: ${{github.action_repository}}/.github/workflows/golang-test-darwin-template.yml@${{ github.ref_name }}
  test-on-pr:
    if: github.event_name == 'pull_request'
    uses: ${{github.action_repository}}/.github/workflows/golang-test-darwin-template.yml@${{ github.ref_name }}
