name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - add-windows-installer

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # It is required for GoReleaser to work properly
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Install modules
        run: go mod tidy
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to Docker hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Download EnvVarUpdate function
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/a/ad/EnvVarUpdate.7z
          file-name: EnvVarUpdate.7z
          location: ${{ github.workspace }}

      -
        name: Extract EnVar plugin
        run: |
          7z x -o"${{ github.workspace }}/client" "${{ github.workspace }}/EnvVarUpdate.7z"
          ls -l

      -
        name: Install makensis
        run: sudo apt update && sudo apt install -y nsis nsis-pluginapi

      -
        name: Generate Windows installer
        run:  makensis -V4 client/installer.nsis
        env:
          APPVER: 0.0.0.10

      -
        name: Upload windows installer to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows-installer.exe
          asset_name: wiretrustee_installer_${{ github.ref }}_windows_amd64.exe
          tag: ${{ github.ref }}