name: Test Infrastructure Docker Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  test-management-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install modules
        run: go mod tidy

      - name: Install modules
        run: go mod tidy

      - name: Run go build
        run: CGO_ENABLED=1 GOARCH=${{ matrix.arch }} go build -o netbird-mgmt ./management

      - name: Run docker build
        run: |
          docker build -t netbird-mgmt -f ./management/